import { Types } from 'mongoose';
import Commission, { CommissionKind } from '../../../database/models/commission.model';
import { AppError } from '../../../utils/errors';
import logger from '../../../utils/logger';
import {
    createVotePaymentIntent, creditBuyerBalance, getPaymentIntentState,
} from '../../../services/clients/payment.service.client';
import { creditEventOrganizerBalance, debitEventOrganizerBalance } from '../../../services/clients/user.service.client';
import { getCommissionConfig } from '../../../services/clients/settings.service.client';
import { organizerUserIdFor } from '../../../services/order.service';
import { AnimCandidate, AnimChallenge } from '../models/challenge.model';
import { AnimResult } from '../models/reward.model';
import { AnimVote, AnimVotePackage, AnimVoteRefund, AnimVoteTransaction, IAnimVoteTransaction } from '../models/vote.model';
import {
    CandidateStatus, ChallengeStatus, FraudReview, RuleTrigger, TeamRole, VoteKind, VoteStatus, VoteTxStatus,
    allowsPaidVotes,
} from '../types';
import { Actor, SYSTEM_ACTOR, audit } from '../lib/audit';
import { assertCanVote, assertVotingOpen, hashSignal, loadVotable, throttle } from './vote.service';
import { asSentence } from '../lib/rules';
import { markBoardDirty } from './board.service';
import { enqueue } from './outbox.service';

const log = logger.getLogger('AnimationPaidVotes');

const SETTLEMENT_LEASE_MS = 10 * 60 * 1000;
/** Purchases a single account may open per hour on one challenge before it is refused. */
const MAX_PURCHASES_PER_HOUR = 30;

// ---------- purchase (§17–§18) ----------

/**
 * Starts a vote-pack purchase. Nothing is credited here: votes exist only once
 * payment-service confirms the payment (§18 — never on the frontend's word).
 * `idempotencyKey` (one per click, generated by the client) makes a double tap
 * or a retried request return the same transaction and payment session.
 */
export const startPurchase = async (args: {
    userId: string; challengeId: string; candidateId: string; packageId: string; idempotencyKey: string; ip?: string; ua?: string;
}) => {
    const key = String(args.idempotencyKey ?? '').trim();
    if (!/^[A-Za-z0-9_-]{8,100}$/.test(key)) throw new AppError('Clé de requête invalide.', 400);
    const existing = await AnimVoteTransaction.findOne({ userId: args.userId, idempotencyKey: key });
    if (existing) {
        if (String(existing.candidateId) !== args.candidateId || String(existing.packageId) !== args.packageId) {
            throw new AppError('Clé de requête déjà utilisée pour un autre achat.', 409, true, 'IDEMPOTENCY_MISMATCH');
        }
        return { transaction: existing, sessionId: existing.paymentSessionId };
    }

    const { challenge, candidate } = await loadVotable(args.challengeId, args.candidateId);
    if (!allowsPaidVotes(challenge.voting.mode)) throw new AppError('Ce défi n’a pas de votes payants.', 409, true, 'NO_PAID_VOTES');
    await assertVotingOpen(challenge);
    if (!challenge.voting.selfVoteAllowed && String(candidate.userId) === args.userId) {
        throw new AppError('Vous ne pouvez pas acheter des votes pour vous-même.', 403, true, 'SELF_VOTE');
    }
    await assertCanVote(challenge, args.userId);
    await throttle(args.userId, args.ip, 'paid');

    if (!Types.ObjectId.isValid(args.packageId)) throw new AppError('Pack introuvable.', 404);
    const pack = await AnimVotePackage.findOne({ _id: args.packageId, challengeId: challenge._id, status: 'ACTIVE' }).lean();
    if (!pack) throw new AppError('Ce pack n’est plus disponible.', 409, true, 'PACKAGE_UNAVAILABLE');
    const now = Date.now();
    if ((pack.availableFrom && new Date(pack.availableFrom).getTime() > now) || (pack.availableUntil && new Date(pack.availableUntil).getTime() <= now)) {
        throw new AppError('Ce pack n’est pas disponible en ce moment.', 409, true, 'PACKAGE_UNAVAILABLE');
    }

    const recent = await AnimVoteTransaction.countDocuments({
        userId: args.userId, challengeId: challenge._id, createdAt: { $gt: new Date(now - 3_600_000) },
    });
    if (recent >= MAX_PURCHASES_PER_HOUR) {
        throw new AppError('Trop d’achats en une heure sur ce défi. Réessayez plus tard.', 429, true, 'PURCHASE_LIMIT');
    }

    const { votePct } = await getCommissionConfig();
    const commissionAmount = Math.round(pack.price * votePct);
    let tx: IAnimVoteTransaction;
    try {
        tx = await AnimVoteTransaction.create({
            organizerId: challenge.organizerId, eventId: challenge.eventId, challengeId: challenge._id,
            candidateId: candidate._id, userId: args.userId, packageId: pack._id,
            packageSnapshot: { label: pack.label, votes: pack.votes, price: pack.price },
            votes: pack.votes, amount: pack.price, currency: pack.currency,
            commissionRate: votePct, commissionAmount, organizerNet: pack.price - commissionAmount,
            status: VoteTxStatus.PENDING, idempotencyKey: key,
            ipHash: hashSignal(args.ip), uaHash: hashSignal(args.ua),
            fraud: { score: 0, flags: [], review: FraudReview.NONE },
        });
    } catch (err: any) {
        if (err?.code === 11000) {
            const raced = await AnimVoteTransaction.findOne({ userId: args.userId, idempotencyKey: key });
            if (raced) return { transaction: raced, sessionId: raced.paymentSessionId };
        }
        throw err;
    }

    try {
        const intent = await createVotePaymentIntent({
            userId: args.userId, amount: pack.price, voteTransactionId: String(tx._id),
            challengeName: challenge.name, votes: pack.votes,
        });
        tx.paymentSessionId = intent.sessionId;
        await tx.save();
    } catch (err) {
        tx.status = VoteTxStatus.FAILED;
        tx.providerStatus = 'INTENT_FAILED';
        await tx.save();
        throw err;
    }
    const { evaluatePurchase } = await import('./fraud.service');
    await evaluatePurchase(tx).catch((e) => log.warn(`fraud pre-check failed: ${(e as Error).message}`));
    return { transaction: tx, sessionId: tx.paymentSessionId };
};

export const getMyTransaction = async (userId: string, txId: string) => {
    if (!Types.ObjectId.isValid(txId)) throw new AppError('Transaction introuvable.', 404);
    const tx = await AnimVoteTransaction.findOne({ _id: txId, userId }).lean();
    if (!tx) throw new AppError('Transaction introuvable.', 404);
    const [challenge, candidate] = await Promise.all([
        AnimChallenge.findById(tx.challengeId).select('name slug eventId').lean(),
        AnimCandidate.findById(tx.candidateId).select('displayName number photoFileId').lean(),
    ]);
    return { transaction: tx, challenge, candidate };
};

// ---------- settlement (§18–§19) ----------

/** The votes can no longer count: the window (plus grace) is over, the result is frozen, or the candidate is out. */
const whyNotCountable = async (tx: IAnimVoteTransaction): Promise<string | null> => {
    const [challenge, candidate, frozen] = await Promise.all([
        AnimChallenge.findById(tx.challengeId).select('status schedule').lean(),
        AnimCandidate.findById(tx.candidateId).select('status').lean(),
        AnimResult.exists({ challengeId: tx.challengeId, status: 'FROZEN' }),
    ]);
    if (!challenge) return 'défi introuvable';
    if (challenge.status === ChallengeStatus.CANCELLED) return 'défi annulé';
    if (frozen) return 'résultat déjà figé';
    if ([ChallengeStatus.RESULTS_PENDING, ChallengeStatus.COMPLETED].includes(challenge.status)) return 'votes clos';
    const closes = challenge.schedule.votingClosesAt ? new Date(challenge.schedule.votingClosesAt).getTime() : Infinity;
    const grace = (challenge.schedule.settlementGraceMin ?? 10) * 60_000;
    if (Date.now() > closes + grace) return 'paiement confirmé après la clôture des votes';
    if (candidate?.status !== CandidateStatus.APPROVED) return 'candidat retiré ou disqualifié';
    return null;
};

/**
 * Settles a vote purchase from payment-service's verified outcome. Exactly
 * once, however many times it is delivered: the claim (settlingAt) admits one
 * settler; the ledger's unique transactionId admits one vote row; the
 * commission and the organizer credit are keyed by the transaction.
 *
 * A late success — payment confirmed after voting closed (+ grace), after the
 * result froze, or for a candidate who left — is refunded, never counted.
 * FAILED/CANCELLED can still turn into SUCCESS (the provider confirms late).
 */
export const settleVoteFromWebhook = async (payload: { sessionId: string; status: string; verifiedAmount?: number }) => {
    const tx = await AnimVoteTransaction.findOne({ paymentSessionId: payload.sessionId });
    if (!tx) return { handled: false };
    if (payload.status === 'SUCCEEDED' && payload.verifiedAmount !== undefined && Math.round(payload.verifiedAmount) !== Math.round(tx.amount)) {
        // payment-service says paid, but not this amount: never credit, put it in front of SBC.
        await AnimVoteTransaction.updateOne({ _id: tx._id, status: VoteTxStatus.PENDING }, {
            $set: { providerStatus: `AMOUNT_MISMATCH:${payload.verifiedAmount}`, 'fraud.review': FraudReview.PENDING },
            $addToSet: { 'fraud.flags': 'AMOUNT_MISMATCH' },
        });
        const { flagAmountMismatch } = await import('./fraud.service');
        await flagAmountMismatch(tx, payload.verifiedAmount);
        log.error(`Vote purchase ${tx._id}: paid ${payload.verifiedAmount} for ${tx.amount} — not credited.`);
        return { handled: true, outcome: 'amount_mismatch' };
    }
    if (tx.status === VoteTxStatus.SUCCESS || tx.status === VoteTxStatus.REFUNDED) return { handled: true, alreadyProcessed: true };

    if (payload.status !== 'SUCCEEDED') {
        await AnimVoteTransaction.updateOne(
            { _id: tx._id, status: VoteTxStatus.PENDING, settlingAt: { $exists: false } },
            { $set: { status: payload.status === 'CANCELED' ? VoteTxStatus.CANCELLED : VoteTxStatus.FAILED, providerStatus: payload.status } },
        );
        return { handled: true, outcome: 'failed' };
    }

    const claimed = await AnimVoteTransaction.findOneAndUpdate(
        {
            _id: tx._id,
            status: { $in: [VoteTxStatus.PENDING, VoteTxStatus.FAILED, VoteTxStatus.CANCELLED] },
            $or: [{ settlingAt: { $exists: false } }, { settlingAt: { $lt: new Date(Date.now() - SETTLEMENT_LEASE_MS) } }],
        },
        { $set: { settlingAt: new Date(), providerStatus: payload.status } },
        { new: true },
    );
    if (!claimed) return { handled: true, alreadyProcessed: true };

    const notCountable = await whyNotCountable(claimed);
    if (notCountable) {
        await AnimVoteTransaction.updateOne({ _id: claimed._id }, { $set: { status: VoteTxStatus.SUCCESS, lateSettlement: true, settledAt: new Date() } });
        log.warn(`Vote purchase ${claimed._id} paid but not countable (${notCountable}) — refunding.`);
        await refundTransaction(SYSTEM_ACTOR, claimed._id, `Votes non comptabilisés : ${notCountable}`);
        return { handled: true, outcome: 'refunded_late' };
    }

    const now = new Date();
    let credited = true;
    try {
        await AnimVote.create({
            organizerId: claimed.organizerId, eventId: claimed.eventId, challengeId: claimed.challengeId,
            candidateId: claimed.candidateId, voterUserId: claimed.userId, kind: VoteKind.PAID,
            quantity: claimed.votes, transactionId: claimed._id, ipHash: claimed.ipHash, uaHash: claimed.uaHash, at: now,
        });
    } catch (err: any) {
        if (err?.code !== 11000) throw err;
        credited = false; // a crashed earlier run already wrote the vote; the recount job heals counters
    }
    if (credited) {
        await Promise.all([
            AnimCandidate.updateOne({ _id: claimed.candidateId }, { $inc: { paidVotes: claimed.votes, totalVotes: claimed.votes }, $set: { reachedTotalAt: now, lastVoteAt: now } }),
            AnimChallenge.updateOne({ _id: claimed.challengeId }, { $inc: { 'counters.paidVotes': claimed.votes, 'counters.paidRevenue': claimed.amount, 'counters.paidTransactions': 1 } }),
        ]);
    }
    await AnimVoteTransaction.updateOne({ _id: claimed._id }, { $set: { status: VoteTxStatus.SUCCESS, settledAt: now, votesCreditedAt: now } });

    try {
        await Commission.updateOne(
            { voteTransactionId: claimed._id },
            { $setOnInsert: {
                kind: CommissionKind.VOTE, voteTransactionId: claimed._id, eventId: claimed.eventId,
                basisAmount: claimed.amount, rate: claimed.commissionRate, amount: claimed.commissionAmount, sbcRevenueBookedAt: now,
            } },
            { upsert: true },
        );
    } catch (err) {
        log.warn(`Vote commission row failed for ${claimed._id}: ${(err as Error).message}`);
    }
    await creditOrganizer(claimed._id);
    await markBoardDirty(claimed.challengeId);

    const { onTrigger } = await import('./reward.service');
    await onTrigger({
        trigger: RuleTrigger.PAID_VOTE, eventId: String(claimed.eventId), challengeId: String(claimed.challengeId),
        userId: String(claimed.userId), subjectKey: `votetx:${claimed._id}`,
    });
    const { evaluateSettled } = await import('./fraud.service');
    await evaluateSettled(claimed._id).catch((e) => log.warn(`fraud check failed: ${(e as Error).message}`));
    return { handled: true, outcome: 'paid', transactionId: String(claimed._id) };
};

/** The organizer's net share, credited immediately like a ticket sale (decision). Idempotent on the reference. */
export const creditOrganizer = async (txId: Types.ObjectId | string) => {
    const tx = await AnimVoteTransaction.findById(txId);
    if (!tx || tx.status !== VoteTxStatus.SUCCESS || tx.lateSettlement || tx.creditedAt || !(tx.organizerNet > 0)) return false;
    try {
        const organizerUserId = await organizerUserIdFor(tx.organizerId);
        if (!organizerUserId) throw new Error(`no account for organizer ${tx.organizerId}`);
        const challenge = await AnimChallenge.findById(tx.challengeId).select('name').lean();
        await creditEventOrganizerBalance({
            userId: organizerUserId,
            amount: tx.organizerNet,
            reference: `event-vote:${tx._id}`,
            description: `Votes « ${challenge?.name ?? 'défi'} » (${tx.votes} votes)`,
        });
        await AnimVoteTransaction.updateOne({ _id: tx._id, creditedAt: { $exists: false } }, { $set: { creditedAt: new Date() } });
        return true;
    } catch (err) {
        log.error(`Organizer credit for vote purchase ${tx._id} failed: ${(err as Error).message} — sweeper will retry.`);
        return false;
    }
};

/** Job: organizer credits that failed on first attempt. */
export const sweepVoteCredits = async (): Promise<number> => {
    const due = await AnimVoteTransaction.find({
        status: VoteTxStatus.SUCCESS, lateSettlement: { $ne: true }, creditedAt: { $exists: false }, organizerNet: { $gt: 0 },
    }).select('_id').limit(100).lean();
    let n = 0;
    for (const t of due) if (await creditOrganizer(t._id)) n++;
    return n;
};

/**
 * Job: purchases whose callback never came. Asks payment-service for the real
 * outcome after 15 min; gives up on unpaid sessions after 24 h (a later
 * success is still honoured by settleVoteFromWebhook — and refunded if late).
 */
export const reconcileVotePayments = async (): Promise<number> => {
    const now = Date.now();
    const pending = await AnimVoteTransaction.find({
        status: VoteTxStatus.PENDING,
        paymentSessionId: { $type: 'string' },
        createdAt: { $lt: new Date(now - 15 * 60_000), $gt: new Date(now - 7 * 86_400_000) },
        $or: [{ reconciledAt: { $exists: false } }, { reconciledAt: { $lt: new Date(now - 10 * 60_000) } }],
    }).sort({ createdAt: 1 }).limit(50).select('_id paymentSessionId createdAt').lean();
    let settled = 0;
    for (const t of pending) {
        try {
            const intent = await getPaymentIntentState(String(t.paymentSessionId));
            await AnimVoteTransaction.updateOne({ _id: t._id }, { $set: { reconciledAt: new Date() } });
            const st = intent?.status;
            if (st === 'SUCCEEDED' || st === 'CONFIRMED') {
                const r = await settleVoteFromWebhook({ sessionId: String(t.paymentSessionId), status: 'SUCCEEDED', verifiedAmount: intent?.amount });
                if ('outcome' in r && r.outcome === 'paid') settled++;
            } else if (st && ['FAILED', 'CANCELED', 'EXPIRED', 'ERROR'].includes(st)) {
                await settleVoteFromWebhook({ sessionId: String(t.paymentSessionId), status: st });
            } else if (now - new Date(t.createdAt).getTime() > 24 * 3_600_000) {
                await AnimVoteTransaction.updateOne({ _id: t._id, status: VoteTxStatus.PENDING }, { $set: { status: VoteTxStatus.CANCELLED, providerStatus: st ?? 'EXPIRED' } });
            }
        } catch (err) {
            log.warn(`reconcile vote tx ${t._id} failed: ${(err as Error).message}`);
        }
    }
    return settled;
};

// ---------- refunds (§39) ----------

/**
 * Refunds one successful purchase in full to the buyer's SBC wallet,
 * commission included (decision). Votes are voided and uncounted, SBC's
 * commission reversed, and the organizer's share debited back (the balance may
 * go negative). Each money movement is keyed by the transaction, so a retry —
 * by the job or an admin — never moves money twice.
 */
export const refundTransaction = async (actor: Actor, txId: Types.ObjectId | string, reason: string) => {
    const tx = await AnimVoteTransaction.findById(txId);
    if (!tx) throw new AppError('Transaction introuvable.', 404);
    if (tx.status !== VoteTxStatus.SUCCESS && tx.status !== VoteTxStatus.REFUNDED) {
        throw new AppError('Seul un achat payé peut être remboursé.', 409, true, 'NOT_REFUNDABLE');
    }
    try {
        await AnimVoteRefund.create({
            voteTransactionId: tx._id, challengeId: tx.challengeId, eventId: tx.eventId, userId: tx.userId,
            amount: tx.amount, reason, initiatedBy: actor.actorUserId && Types.ObjectId.isValid(actor.actorUserId) ? actor.actorUserId : undefined,
        });
    } catch (err: any) {
        if (err?.code !== 11000) throw err; // already started: resume it below
    }

    await AnimVoteTransaction.updateOne(
        { _id: tx._id, status: VoteTxStatus.SUCCESS },
        { $set: { status: VoteTxStatus.REFUNDED, refundedAt: new Date() } },
    );
    // Uncount the votes. Runs on every attempt — COUNTED → VOID is itself the
    // once-only claim — so a crash right after the status flip can't leave
    // refunded votes on the board.
    if (tx.votesCreditedAt && !tx.lateSettlement) {
        const voided = await AnimVote.findOneAndUpdate(
            { transactionId: tx._id, kind: VoteKind.PAID, status: VoteStatus.COUNTED },
            { $set: { status: VoteStatus.VOID, voidReason: reason, voidedBy: actor.actorUserId && Types.ObjectId.isValid(actor.actorUserId) ? actor.actorUserId : undefined } },
        );
        if (voided) {
            await Promise.all([
                AnimCandidate.updateOne({ _id: tx.candidateId }, { $inc: { paidVotes: -tx.votes, totalVotes: -tx.votes } }),
                AnimChallenge.updateOne({ _id: tx.challengeId }, { $inc: { 'counters.paidVotes': -tx.votes, 'counters.paidRevenue': -tx.amount, 'counters.paidTransactions': -1 } }),
            ]);
            await markBoardDirty(tx.challengeId);
        }
        await Commission.updateOne({ voteTransactionId: tx._id, reversedAt: { $exists: false } }, { $set: { reversedAt: new Date() } });
    }
    await audit({
        actor, action: 'vote.refund', targetType: 'vote_transaction', targetId: tx._id,
        organizerId: tx.organizerId, eventId: tx.eventId, challengeId: tx.challengeId,
        after: { amount: tx.amount, votes: tx.votes }, reason,
    });
    await processRefundMoney(tx._id);
    return AnimVoteTransaction.findById(tx._id);
};

/** The money side of a refund; re-runnable until COMPLETED. */
export const processRefundMoney = async (txId: Types.ObjectId | string) => {
    const refund = await AnimVoteRefund.findOne({ voteTransactionId: txId });
    const tx = await AnimVoteTransaction.findById(txId);
    if (!refund || !tx || refund.status === 'COMPLETED') return;
    await AnimVoteRefund.updateOne({ _id: refund._id }, { $inc: { attempts: 1 } });
    try {
        if (!refund.walletCreditedAt) {
            const challenge = await AnimChallenge.findById(tx.challengeId).select('name').lean();
            await creditBuyerBalance({
                userId: String(tx.userId), amount: tx.amount,
                description: `Remboursement votes « ${challenge?.name ?? 'défi'} »`,
                reference: `event-vote-refund:${tx._id}`, eventId: String(tx.eventId),
            });
            await AnimVoteRefund.updateOne({ _id: refund._id }, { $set: { walletCreditedAt: new Date() } });
        }
        if (tx.creditedAt && !refund.organizerDebitedAt && tx.organizerNet > 0) {
            const organizerUserId = await organizerUserIdFor(tx.organizerId);
            if (!organizerUserId) throw new Error(`no account for organizer ${tx.organizerId}`);
            await debitEventOrganizerBalance({
                userId: organizerUserId, amount: tx.organizerNet,
                reference: `event-vote-refund:${tx._id}`, description: `Remboursement de votes (${tx.votes} votes)`,
            });
            await AnimVoteRefund.updateOne({ _id: refund._id }, { $set: { organizerDebitedAt: new Date() } });
        }
        await AnimVoteRefund.updateOne({ _id: refund._id }, { $set: { status: 'COMPLETED', completedAt: new Date(), lastError: undefined } });
        const challengeName = (await AnimChallenge.findById(tx.challengeId).select('name').lean())?.name ?? 'défi';
        await enqueue({
            dedupeKey: `anim-vote-refunded:${tx._id}`, kind: 'anim-vote-refunded', userId: tx.userId, eventId: tx.eventId,
            subject: '💸 Achat de votes remboursé',
            body: `${tx.amount} XAF ont été crédités sur votre solde SBC pour vos votes à « ${challengeName} ». Motif : ${asSentence(refund.reason)}`,
            data: { amount: tx.amount, reason: refund.reason },
        });
    } catch (err) {
        await AnimVoteRefund.updateOne({ _id: refund._id }, { $set: { status: 'FAILED', lastError: (err as Error).message } });
        log.error(`Vote refund ${tx._id} failed: ${(err as Error).message} — will retry.`);
    }
};

/** Job: refunds whose money side failed. */
export const retryVoteRefunds = async (): Promise<number> => {
    const due = await AnimVoteRefund.find({ status: { $in: ['PENDING', 'FAILED'] }, attempts: { $lt: 20 }, updatedAt: { $lt: new Date(Date.now() - 60_000) } }).limit(50).select('voteTransactionId').lean();
    for (const r of due) await processRefundMoney(r.voteTransactionId);
    return due.length;
};

/** Cancellation: every successful purchase of the challenge is refunded. Returns how many. */
const refundAll = async (actor: Actor, filter: Record<string, unknown>, reason: string, what: string) => {
    const txs = await AnimVoteTransaction.find({ ...filter, status: VoteTxStatus.SUCCESS }).select('_id').lean();
    let n = 0;
    for (const t of txs) {
        try {
            await refundTransaction(actor, t._id, reason);
            n++;
        } catch (err) {
            log.error(`refund of ${t._id} (${what}) failed: ${(err as Error).message}`);
        }
    }
    // Purchases still awaiting payment will settle as "late" and be refunded automatically.
    return n;
};

export const refundChallengeTransactions = (actor: Actor, challengeId: Types.ObjectId | string, reason: string) =>
    refundAll(actor, { challengeId }, reason, 'challenge cancelled');

/**
 * A candidate who leaves the race (withdrawal, disqualification by the team)
 * takes their paid votes with them: the buyers are refunded in full, like a
 * cancellation. Otherwise disqualifying a well-supported candidate would let
 * the organizer keep money for votes that no longer count.
 */
export const refundCandidateTransactions = (actor: Actor, candidateId: Types.ObjectId | string, reason: string) =>
    refundAll(actor, { candidateId }, reason, 'candidate out');

/**
 * Job: paid votes still standing on a cancelled challenge or an eliminated
 * candidate (a crash interrupted the refund loop). Uses the counters to find
 * them cheaply. Purchases SBC confirmed as fraud are left alone — the review
 * decided whether to refund those.
 */
export const sweepStrandedPaidVotes = async (): Promise<number> => {
    const [challenges, candidates] = await Promise.all([
        AnimChallenge.find({ status: ChallengeStatus.CANCELLED, 'counters.paidTransactions': { $gt: 0 } }).select('_id').limit(50).lean(),
        AnimCandidate.find({ status: { $in: [CandidateStatus.WITHDRAWN, CandidateStatus.DISQUALIFIED] }, paidVotes: { $gt: 0 } }).select('_id').limit(50).lean(),
    ]);
    if (!challenges.length && !candidates.length) return 0;
    const settledBefore = new Date(Date.now() - 2 * 60_000); // leave the live paths room to finish
    const base = { settledAt: { $lt: settledBefore }, 'fraud.review': { $ne: FraudReview.CONFIRMED } };
    let n = 0;
    for (const c of challenges) n += await refundAll(SYSTEM_ACTOR, { ...base, challengeId: c._id }, 'Défi annulé', 'sweep: challenge cancelled');
    for (const c of candidates) n += await refundAll(SYSTEM_ACTOR, { ...base, candidateId: c._id }, 'Candidat retiré du défi', 'sweep: candidate out');
    return n;
};

/** SBC admin refund of a single purchase (§20 review outcome, or a support case). */
export const adminRefund = (actorUserId: string, txId: string, reason: string) => {
    if (!reason?.trim()) throw new AppError('Indiquez le motif du remboursement.', 400);
    return refundTransaction({ actorUserId, role: TeamRole.SBC_ADMIN }, txId, reason.trim());
};
